[workspace]
resolver = "3"
members = [
  "add_one",
  "adder",
  "aggregator",
  "another_function",
  "cargo",
  "closures",
  "enums",
  "errors",
  "generics",
  "guessing_game",
  "hash_map", "messenger",
  "minigrep",
  "ownership", "pointers",
  "rectangles",
  "strings",
  "structs",
  "variables",
  "vectors", "weak_pointers",
]

[workspace.package]
edition = "2024"

[workspace.dependencies]
rand = "0.8.5"

# This configuration allows all the projects to be built from the root
# while maintaining their independence as binary crates
